import Ajv from "ajv";

const ajv = new Ajv();

/**
 * Dynamically imports a module and extracts a specific export.
 * @param {string} url - The module URL to import
 * @param {string} exportName - The named export to extract
 * @param {*} defaultValue - Value to return on failure
 * @returns {Promise<*>} - The exported value or default
 */
async function importFromUrl(url, exportName, defaultValue = null) {
    try {
        const module = await import(/* webpackIgnore: true */ url);
        if (!Object.hasOwn(module, exportName)) {
            throw new Error(`No ${exportName} in module`);
        }
        return module[exportName];
    } catch (error) {
        console.error(`Failed to import ${exportName} from ${url}: ${error}`);
        return defaultValue;
    }
}

// Consolidated dynamic imports - all load in parallel
const [
    isTrueBoolean,
    SlashCommandParser,
    SlashCommand,
    ARGUMENT_TYPE,
    SlashCommandArgument,
    SlashCommandNamedArgument
] = await Promise.all([
    importFromUrl('/scripts/utils.js', 'isTrueBoolean'),
    importFromUrl('/scripts/slash-commands/SlashCommandParser.js', 'SlashCommandParser'),
    importFromUrl('/scripts/slash-commands/SlashCommand.js', 'SlashCommand'),
    importFromUrl('/scripts/slash-commands/SlashCommandArgument.js', 'ARGUMENT_TYPE'),
    importFromUrl('/scripts/slash-commands/SlashCommandArgument.js', 'SlashCommandArgument'),
    importFromUrl('/scripts/slash-commands/SlashCommandArgument.js', 'SlashCommandNamedArgument'),
]);

const objBoolOrThrow = {
    bool: (valid) => {
        return valid;
    },
    throw: (valid) => {
        if (!valid) {
            throw new TypeError('Validation Error!');
        }
        return valid;
    },
};

/**
 * Parses a value string into its appropriate JavaScript type.
 * Attempts JSON parsing first, then numeric conversion, then boolean strings.
 * @param {string} value - The value string to parse
 * @returns {*} - The parsed value in its appropriate type
 */
function parseValue(value) {
    // Try JSON parsing first (handles objects, arrays, numbers, booleans, null)
    try {
        return JSON.parse(value);
    } catch {
        // Try numeric conversion for plain numbers
        const numericValue = parseFloat(value);
        if (!isNaN(numericValue)) {
            return numericValue;
        }
        // Handle boolean strings
        if (value === 'true' || value === 'false') {
            return isTrueBoolean(value);
        }
        // Return as string if no other conversion succeeds
        return value;
    }
}

/**
 * Validates a value against a JSON schema using Ajv.
 * Handles both pre-parsed and string-formatted schemas/values.
 * @param {Object} args - Arguments containing the schema
 * @param {string|Object} value - Value to validate (string or parsed value)
 * @returns {boolean} - Whether the value passes validation
 */
async function validateVar(args, value) {
    // Parse schema: try JSON first, fallback to object if already parsed
    const schema = typeof args.schema === 'string'
        ? JSON.parse(args.schema)
        : args.schema;


    return objBoolOrThrow[args.throw ? 'throw' : 'bool'](ajv.validate(schema, parseValue(value)));
}

async function validateJSON(args, value) {
    const schema = typeof value === 'string'
        ? JSON.parse(value)
        : value;

    // Validate schema before attempting validation
    return ajv.validateSchema(schema, args.throw ? true : false)
}

SlashCommandParser.addCommandObject(SlashCommand.fromProps({
    name: "silly-validator",
    aliases: ["st-validate"],
    callback: validateVar,
    namedArgumentList: [
        SlashCommandNamedArgument.fromProps({
            name: "schema",
            description: "schema to use for validation",
            typeList: [ARGUMENT_TYPE.DICTIONARY],
            isRequired: true,
            acceptsMultiple: false,
        }),
        SlashCommandNamedArgument.fromProps({
            name: "throw",
            description: "Whether to throw an error on validation failure",
            typeList: [ARGUMENT_TYPE.BOOLEAN],
        }),
    ],
    unnamedArgumentList: [
        SlashCommandArgument.fromProps({
            description: "value to validate",
            typeList: [ARGUMENT_TYPE.STRING, ARGUMENT_TYPE.NUMBER, ARGUMENT_TYPE.BOOLEAN, ARGUMENT_TYPE.LIST, ARGUMENT_TYPE.DICTIONARY],
            isRequired: true,
            acceptsMultiple: false,
        }),
    ],
    splitUnnamedArgument: false,
    helpString: /*html*/`
    <div>
        Validate variables through Ajv and return a boolean value indicating whether the variable is valid or not.
        <br/>Helpful for validating datatypes generated by LLMs.
    </div>
    <div>
        <ul>
            <li><pre><code class="language-stscript">// With silly-validator you can validate variables using JSON Schemas. |
// The validator will return a boolean value indicating whether the variable is valid or not. |

/let schema = { "type": "string" } |
/let value = "Hello, World!" |

/silly-validator schema={{var::schema}} {{var::value}} |

/echo {{pipe}} |
// Output: true</code></pre></li>
        </ul>
    </div>
    `,
    returns: 'boolean'
}));

SlashCommandParser.addCommandObject(SlashCommand.fromProps({
    name: "silly-validate-schema",
    callback: validateJSON,
    namedArgumentList: [
        SlashCommandNamedArgument.fromProps({
            name: "throw",
            description: "Whether to throw an error on validation failure",
            typeList: [ARGUMENT_TYPE.BOOLEAN],
        }),
    ],
    unnamedArgumentList: [
        SlashCommandArgument.fromProps({
            description: "schema to use for validation",
            typeList: [ARGUMENT_TYPE.DICTIONARY],
            isRequired: true,
            acceptsMultiple: false,
        }),
    ],
    splitUnnamedArgument: false,
    helpString: /*html*/`
    <div>
        Validate a JSON schema using Ajv.
        <br/>Returns true if the schema is valid, false otherwise.
    </div>
    <div>
        <ul>
            <li><pre><code class="language-stscript">// With silly-validate-schema you can validate JSON schemas to make sure they are structurally correct. |

/silly-validate-schema { "type": "string" } |
/echo {{pipe}}</code></pre></li>
        </ul>
    </div>
    `,
    returns: 'boolean'
}));
